name: milestone
on: 
  issues:
    types: demilestoned
jobs:
  demilestoned:
    runs-on: [ubuntu-latest]
    steps:
      - name: get issue
        run: |
          echo ${{ github.event.issue.url }}
      - name: add label
        run: |
          curl -v -u admin:${{ secrets.GITHUB_TOKEN }} -H "Accept: application/vnd.github.antiope-preview+json" -d '{"labels": ["Needs Milestone"]}' ${{ github.event.issue.url }}/labels
